### PR TITLE
Fix/station partionning

### PR DESCRIPTION
**Pull request by louisPoulain**

### CODE REVIEW

**Comment by louisPoulain** [comment]
We still to try on our 2 systems @dnerini but looking at [the documentation](https://numpy.org/doc/stable/reference/random/bit_generators/pcg64.html), we should be fine.

**Comment by louisPoulain** [comment]
As discussed, we need to coordinate to see whether this change is working.
Here are the station_wind_speed.json and the train_val_test.json. Can you join yours @dnerini or tell me if you get the same results (with seed 42 and the PCG64) ?
[stations_wind_speed.json](https://github.com/user-attachments/files/16056077/stations_wind_speed.json)
[train_validation_test.json](https://github.com/user-attachments/files/16056078/train_validation_test.json)

**Comment by louisPoulain** [comment]
At the moment, this PR requires a bit of testing as it does not seem to produce consistent results.

**Comment by louisPoulain** [comment]
@dnerini This PR is now ready for review too. My errors were due to a misuse of PCG64

**Comment by dnerini** [comment]
> As discussed, we need to coordinate to see whether this change is working. Here are the station_wind_speed.json and the train_val_test.json. Can you join yours @dnerini or tell me if you get the same results (with seed 42 and the PCG64) ? [stations_wind_speed.json](https://github.com/user-attachments/files/16056077/stations_wind_speed.json) [train_validation_test.json](https://github.com/user-attachments/files/16056239/train_validation_test.json)

**Review by dnerini — APPROVED** [review]

**Pull request merged**
